package com.estate.core.entity;
// Generated May 9, 2021, 8:36:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Categorys generated by hbm2java
 */
@Entity
@Table(name = "categorys", schema = "public")
public class Categorys implements java.io.Serializable {

	private int id;
	private int parentId;
	private String title;
	private String slug;
	private Integer orders;
	private String metakey;
	private String metadesc;
	private Date createdAt;
	private boolean maincontainer;
	private boolean dealcontainer;
	private boolean container1;
	private boolean container2;
	private boolean requestcontainer;
	private boolean itemcontainer;
	private boolean servicecontainer;
	private boolean regioncontainer;
	private int status;

	public Categorys() {
	}

	public Categorys(int id, int parentId, String title, String slug, boolean maincontainer, boolean dealcontainer,
			boolean container1, boolean container2, boolean requestcontainer, boolean itemcontainer,
			boolean servicecontainer, boolean regioncontainer, int status) {
		this.id = id;
		this.parentId = parentId;
		this.title = title;
		this.slug = slug;
		this.maincontainer = maincontainer;
		this.dealcontainer = dealcontainer;
		this.container1 = container1;
		this.container2 = container2;
		this.requestcontainer = requestcontainer;
		this.itemcontainer = itemcontainer;
		this.servicecontainer = servicecontainer;
		this.regioncontainer = regioncontainer;
		this.status = status;
	}

	public Categorys(int id, int parentId, String title, String slug, Integer orders, String metakey, String metadesc,
			Date createdAt, boolean maincontainer, boolean dealcontainer, boolean container1, boolean container2,
			boolean requestcontainer, boolean itemcontainer, boolean servicecontainer, boolean regioncontainer,
			int status) {
		this.id = id;
		this.parentId = parentId;
		this.title = title;
		this.slug = slug;
		this.orders = orders;
		this.metakey = metakey;
		this.metadesc = metadesc;
		this.createdAt = createdAt;
		this.maincontainer = maincontainer;
		this.dealcontainer = dealcontainer;
		this.container1 = container1;
		this.container2 = container2;
		this.requestcontainer = requestcontainer;
		this.itemcontainer = itemcontainer;
		this.servicecontainer = servicecontainer;
		this.regioncontainer = regioncontainer;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "parent_id", nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "slug", nullable = false)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "orders")
	public Integer getOrders() {
		return this.orders;
	}

	public void setOrders(Integer orders) {
		this.orders = orders;
	}

	@Column(name = "metakey")
	public String getMetakey() {
		return this.metakey;
	}

	public void setMetakey(String metakey) {
		this.metakey = metakey;
	}

	@Column(name = "metadesc")
	public String getMetadesc() {
		return this.metadesc;
	}

	public void setMetadesc(String metadesc) {
		this.metadesc = metadesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "maincontainer", nullable = false)
	public boolean isMaincontainer() {
		return this.maincontainer;
	}

	public void setMaincontainer(boolean maincontainer) {
		this.maincontainer = maincontainer;
	}

	@Column(name = "dealcontainer", nullable = false)
	public boolean isDealcontainer() {
		return this.dealcontainer;
	}

	public void setDealcontainer(boolean dealcontainer) {
		this.dealcontainer = dealcontainer;
	}

	@Column(name = "container1", nullable = false)
	public boolean isContainer1() {
		return this.container1;
	}

	public void setContainer1(boolean container1) {
		this.container1 = container1;
	}

	@Column(name = "container2", nullable = false)
	public boolean isContainer2() {
		return this.container2;
	}

	public void setContainer2(boolean container2) {
		this.container2 = container2;
	}

	@Column(name = "requestcontainer", nullable = false)
	public boolean isRequestcontainer() {
		return this.requestcontainer;
	}

	public void setRequestcontainer(boolean requestcontainer) {
		this.requestcontainer = requestcontainer;
	}

	@Column(name = "itemcontainer", nullable = false)
	public boolean isItemcontainer() {
		return this.itemcontainer;
	}

	public void setItemcontainer(boolean itemcontainer) {
		this.itemcontainer = itemcontainer;
	}

	@Column(name = "servicecontainer", nullable = false)
	public boolean isServicecontainer() {
		return this.servicecontainer;
	}

	public void setServicecontainer(boolean servicecontainer) {
		this.servicecontainer = servicecontainer;
	}

	@Column(name = "regioncontainer", nullable = false)
	public boolean isRegioncontainer() {
		return this.regioncontainer;
	}

	public void setRegioncontainer(boolean regioncontainer) {
		this.regioncontainer = regioncontainer;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
