package com.estate.core.entity;
// Generated May 9, 2021, 8:36:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contacts generated by hbm2java
 */
@Entity
@Table(name = "contacts", schema = "public")
public class Contacts implements java.io.Serializable {

	private int id;
	private String fullname;
	private String email;
	private String title;
	private String phone;
	private String detail;
	private String image;
	private Date createdAt;
	private int status;

	public Contacts() {
	}

	public Contacts(int id, String fullname, String email, String title, String phone, String detail, int status) {
		this.id = id;
		this.fullname = fullname;
		this.email = email;
		this.title = title;
		this.phone = phone;
		this.detail = detail;
		this.status = status;
	}

	public Contacts(int id, String fullname, String email, String title, String phone, String detail, String image,
			Date createdAt, int status) {
		this.id = id;
		this.fullname = fullname;
		this.email = email;
		this.title = title;
		this.phone = phone;
		this.detail = detail;
		this.image = image;
		this.createdAt = createdAt;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "fullname", nullable = false)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "phone", nullable = false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "detail", nullable = false)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
