package com.estate.core.entity;
// Generated May 9, 2021, 8:36:41 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", schema = "public")
public class Products implements java.io.Serializable {

	private int id;
	private String productId;
	private Integer categoryId;
	private String title;
	private String description;
	private String slug;
	private String metakey;
	private String metadesc;
	private BigDecimal price;
	private BigDecimal pricesale;
	private BigDecimal discount;
	private String position;
	private String direction;
	private Date createdAt;
	private String image;
	private String area;
	private String address;
	private String phone;
	private String customer;
	private BigDecimal room;
	private boolean maincontainer;
	private boolean dealcontainer;
	private boolean container1;
	private boolean container2;
	private boolean requestcontainer;
	private boolean itemcontainer;
	private boolean servicecontainer;
	private boolean regioncontainer;
	private int status;

	public Products() {
	}

	public Products(int id, String productId, String title, String slug, BigDecimal price, String position,
			String direction, String image, String area, String address, String phone, String customer,
			boolean maincontainer, boolean dealcontainer, boolean container1, boolean container2,
			boolean requestcontainer, boolean itemcontainer, boolean servicecontainer, boolean regioncontainer,
			int status) {
		this.id = id;
		this.productId = productId;
		this.title = title;
		this.slug = slug;
		this.price = price;
		this.position = position;
		this.direction = direction;
		this.image = image;
		this.area = area;
		this.address = address;
		this.phone = phone;
		this.customer = customer;
		this.maincontainer = maincontainer;
		this.dealcontainer = dealcontainer;
		this.container1 = container1;
		this.container2 = container2;
		this.requestcontainer = requestcontainer;
		this.itemcontainer = itemcontainer;
		this.servicecontainer = servicecontainer;
		this.regioncontainer = regioncontainer;
		this.status = status;
	}

	public Products(int id, String productId, Integer categoryId, String title, String description, String slug,
			String metakey, String metadesc, BigDecimal price, BigDecimal pricesale, BigDecimal discount,
			String position, String direction, Date createdAt, String image, String area, String address, String phone,
			String customer, BigDecimal room, boolean maincontainer, boolean dealcontainer, boolean container1,
			boolean container2, boolean requestcontainer, boolean itemcontainer, boolean servicecontainer,
			boolean regioncontainer, int status) {
		this.id = id;
		this.productId = productId;
		this.categoryId = categoryId;
		this.title = title;
		this.description = description;
		this.slug = slug;
		this.metakey = metakey;
		this.metadesc = metadesc;
		this.price = price;
		this.pricesale = pricesale;
		this.discount = discount;
		this.position = position;
		this.direction = direction;
		this.createdAt = createdAt;
		this.image = image;
		this.area = area;
		this.address = address;
		this.phone = phone;
		this.customer = customer;
		this.room = room;
		this.maincontainer = maincontainer;
		this.dealcontainer = dealcontainer;
		this.container1 = container1;
		this.container2 = container2;
		this.requestcontainer = requestcontainer;
		this.itemcontainer = itemcontainer;
		this.servicecontainer = servicecontainer;
		this.regioncontainer = regioncontainer;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "product_id", nullable = false)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "category_id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "title", nullable = false, length = 11255)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 11255)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "slug", nullable = false, length = 11255)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "metakey", length = 11255)
	public String getMetakey() {
		return this.metakey;
	}

	public void setMetakey(String metakey) {
		this.metakey = metakey;
	}

	@Column(name = "metadesc", length = 11255)
	public String getMetadesc() {
		return this.metadesc;
	}

	public void setMetadesc(String metadesc) {
		this.metadesc = metadesc;
	}

	@Column(name = "price", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "pricesale", precision = 131089, scale = 0)
	public BigDecimal getPricesale() {
		return this.pricesale;
	}

	public void setPricesale(BigDecimal pricesale) {
		this.pricesale = pricesale;
	}

	@Column(name = "discount", precision = 131089, scale = 0)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "position", nullable = false, length = 11255)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "direction", nullable = false)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "area", nullable = false, length = 11255)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "address", nullable = false, length = 1255)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", nullable = false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "customer", nullable = false)
	public String getCustomer() {
		return this.customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	@Column(name = "room", precision = 131089, scale = 0)
	public BigDecimal getRoom() {
		return this.room;
	}

	public void setRoom(BigDecimal room) {
		this.room = room;
	}

	@Column(name = "maincontainer", nullable = false)
	public boolean isMaincontainer() {
		return this.maincontainer;
	}

	public void setMaincontainer(boolean maincontainer) {
		this.maincontainer = maincontainer;
	}

	@Column(name = "dealcontainer", nullable = false)
	public boolean isDealcontainer() {
		return this.dealcontainer;
	}

	public void setDealcontainer(boolean dealcontainer) {
		this.dealcontainer = dealcontainer;
	}

	@Column(name = "container1", nullable = false)
	public boolean isContainer1() {
		return this.container1;
	}

	public void setContainer1(boolean container1) {
		this.container1 = container1;
	}

	@Column(name = "container2", nullable = false)
	public boolean isContainer2() {
		return this.container2;
	}

	public void setContainer2(boolean container2) {
		this.container2 = container2;
	}

	@Column(name = "requestcontainer", nullable = false)
	public boolean isRequestcontainer() {
		return this.requestcontainer;
	}

	public void setRequestcontainer(boolean requestcontainer) {
		this.requestcontainer = requestcontainer;
	}

	@Column(name = "itemcontainer", nullable = false)
	public boolean isItemcontainer() {
		return this.itemcontainer;
	}

	public void setItemcontainer(boolean itemcontainer) {
		this.itemcontainer = itemcontainer;
	}

	@Column(name = "servicecontainer", nullable = false)
	public boolean isServicecontainer() {
		return this.servicecontainer;
	}

	public void setServicecontainer(boolean servicecontainer) {
		this.servicecontainer = servicecontainer;
	}

	@Column(name = "regioncontainer", nullable = false)
	public boolean isRegioncontainer() {
		return this.regioncontainer;
	}

	public void setRegioncontainer(boolean regioncontainer) {
		this.regioncontainer = regioncontainer;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
